apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m8qslpl5h-nodejs 
  janus-idp.io/tekton: m8qslpl5h-nodejs
  backstage.io/kubernetes-id: m8qslpl5h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m8qslpl5h-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml